[package]
name = "arr_deque"
version = "0.4.3"
authors = ["Nossie531"]
edition = "2024"
description = "Deque implemented by array."
repository = "https://github.com/nossie531/arr_deque"
license = "MIT"
keywords = ["deque"]
categories = ["no-std", "data-structures"]

[dependencies]
rich_range = "0.4"
subject = "0.1"

[dev-dependencies]
rand = "0.9"
rand_pcg = "0.9"
test_panic = "0.8"
drop_tracer = "0.6"

[features]
default = ["std"]
std = ["alloc"]
alloc = []
